---
version: "3.3"

services:
  server:
    image: nginx:alpine

    deploy:
      mode: replicated
      replicas: 1

      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:trash.zw.s"
    volumes:
      - $HOME/nginx/trash:/srv/http/trash:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
...
# vim: ts=2 sts=1 sw=2
