---
version: "3.3"

services:
  server:
    image: mobz/elasticsearch-head:5-alpine

    deploy:
      mode: replicated
      replicas: 1

      labels:
        - "traefik.port=9100"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:head.zw.s"

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
...
# vim: ts=2 sts=1 sw=2
