version: "3.1"
services:
  grafana:
    image: grafana/grafana:5.0.4

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.port=3000"
        - "traefik.protocol=http"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:grafana.zw.s"

    volumes:
      - grafana_data:/var/lib/grafana

    environment:
      - GF_SERVER_ROOT_URL=http://grafana.zw.s
      - GF_SECURITY_ADMIN_PASSWORD=supersecrete
      - GF_USERS_ALLOW_SIGN_UP=false

    networks:
      - internal
      - traefik-net
      - prometheus-net

  core:
    image: prom/prometheus:v2.2.1

    networks:
      prometheus-net:
        aliases:
          - core.prometheus
      traefik-net:
      internal:
        aliases:
          - prometheus

    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    extra_hosts:
      - "zw.s:10.10.11.184"

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.port=9090"
        - "traefik.protocol=http"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:prometheus.zw.s"

volumes:
  grafana_data:

  prometheus_data:

networks:
  internal:
    driver: overlay
  traefik-net:
    external: true
  prometheus-net:
    external: true

# vim: ts=2 sts=2 sw=2
