# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
  # Scrape Prometheus itself every 5 seconds.
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: 
        - localhost:9090

  # Scrape the Node Exporter every 5 seconds.
  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: 
        - zw.s:9100

  # Scrape docker metrics
  - job_name: docker
    scrape_interval: 15s
    static_configs:
      - targets: 
        - zw.s:9323

  # Scrape docker containers metrics
  - job_name: dockercont
    scrape_interval: 15s
    static_configs:
      - targets: 
        - docker.exporter:8081
