---
version: "3.2"

services:
  indexer:
    image: zzazab/godoc:1.8.3-alpine

    command:
      - -index
      - -index_throttle
      - "0.002"
      - -index_files
      - /var/index/indexed
      - -write_index
      - /var/index/indexed

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 24h

    volumes:
      - $HOME/dev/goroot/src:/go/src
      - index:/var/index

  server:
    image: zzazab/godoc:1.8.3-alpine

    command:
      - -play
      - -index_files
      - /var/index/indexed
      - -http=:6060

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=6060"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:doc.zw.s"

    volumes:
      - /home/persienko/dev/goroot/src:/go/src
      - index:/var/index

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

volumes:
  index:
...
# vim: ts=2 sts=1 sw=2
