---
version: "3.2"

services:
  traefik:
    image: traefik:1.6.4-alpine

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:traefik.zw.s"

    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

      - target: 443
        published: 443
        protocol: tcp
        mode: host

    networks:
      - traefik-net

    secrets:
      - zws_crt
      - zws_key
      - ca

networks:
  traefik-net:
    external: true


secrets:
  zws_crt:
    external: true
  zws_key:
    external: true
  ca:
    external: true
...
# vim: ts=2 sts=1 sw=2
