---
version: "3.2"

services:
  traefik:
    image: traefik:1.5.4-alpine

    command:
      - --web

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.port=8080"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:traefik.zw.s"

    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

      - target: 443
        published: 443
        protocol: tcp
        mode: host

    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

...
# vim: ts=2 sts=1 sw=2
