debug = false
rootCAs = ["/run/secrets/ca"]
defaultEntryPoints = ["http"]
logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.web]
    address = ":8080"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/run/secrets/zws_crt"
      KeyFile = "/run/secrets/zws_key" 

[accessLog]
  filePath = "/tmp/access.log"
  format = "common"

  [accessLog.filters]
    statusCodes = ["300-600"]
    retryAttempts = true

[api]
  entryPoint = "web"
  dashboard = true
  debug = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "traefik"
  watch = true
  swarmmode = true

# vim: ft=toml ts=2 sts=2 sw=2
