---
version: "3.2"

services:
  nginx:
    image: nginx:1.13-alpine

    ports:
      - 80

    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 24h

      labels:
        - "traefik.port=80"
        - "traefik.docker.network=traefik-net"
        - "traefik.frontend.rule=Host:know.zw.s"

    volumes:
      - $HOME/know/public:/srv/http:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

volumes:
  index:
...
# vim: ts=2 sts=1 sw=2
